### ISSUE TITLE
Problem z proxy w Selenium

### ISSUE THREAD

**Issue by mackeysec** [gregxsunday/xss-scanner#1]
Cześć, zedytowałem kod w taki sposób, aby cały ruch, który przechodzi przez "stworzoną" przeglądarkę Selenium, odbywał się poprzez poprzez proxy i trafiał do Burpa.

Zedytowany kod wygląda tak (funkcja create_driver())

    proxy = "127.0.0.1:8080"
    options = webdriver.ChromeOptions()
    options.add_argument('--headless')
    options.add_argument('--no-sandbox')
    options.add_argument('--proxy-server=%s' % proxy)
    driver = webdriver.Chrome('/usr/bin/chromedriver',chrome_options=options)
    return driver

Po dodaniu linijki np.

`driver.get("https://google.com")`

wysłane zapytanie do strony podanej wyżej jest przepuszczane przez proxy, jednak wysyłane requesty wraz z payloadmi, które sa zaimplementowane w dalszych funkcjach, nie przechodzą przez ten ruch.

Jest jakaś możliwość przepuszczenia tych requestów wysyłanych razem z payloadmi przez proxy?

Dzięki z góry za pomoc!

**Comment by mackeysec** [comment]
Po ponownej analizie kodu, wszystko działa poprawnie.

```
proxy = "127.0.0.1:8080"
options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--proxy-server=%s' % proxy)
driver = webdriver.Chrome('/usr/bin/chromedriver',chrome_options=options)
```

**Comment by gregxsunday** [comment]
@mackeysec co było problemem?

**Comment by mackeysec** [comment]
Po kilku zmianach dalszym kodzie funkcji **is_alert_present**, dodałem linijkę z proxy i zadziałało, więc nie jestem w stanie powiedzieć co dokładnie było nie tak.
